# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe3e2c73bb99c0e012880f63630d8b00d479342528bf4e75c944c84b6d4af184e7f4c28b0055f6ad06e4b2c50f819b39c90ab5e91eb2a11f3dc02a4b9837119

test:
  secret_key_base: 742caccc655c2cc323a59def10ce76682f37b01aae1764925fff74c74614631367678e0736b69b66de6719634f524feec5e3bb88e387b6bcc9bb468b7d4f74fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
